security:
  auth:
    username: user_name
    whitelist: /, /v2/api-docs, /swagger-resources, /swagger-resources/**, /configuration/ui,
      /configuration/security, /swagger-ui.html, /webjars/**, /api/public/**
    client_id: client_id
    connection_timeout: '60'
    read_timeout: '60'
    client_password: client_password
    url: http://localhost:8081/oauth/check_token
  public-pattern: /api/public/**
spring:
  mail:
    username: username
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
          timeout: '5000'
    host: smtp.gmail.com
    protocol: smtp
    password: password
    host_address: host_address
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '1200000'
      pool-name: data-source
      minimum-idle: '2'
    password: '2105'
    username: root
    url: jdbc:mysql://localhost:3306/keyist?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  mvc:
    throw-exception-if-no-handler-found: 'true'
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQLDialect
server:
  error:
    whitelabel:
      enabled: 'true'
  port: '8080'
swagger:
  contact:
    email: antkaynak1@gmail.com
    url: https://www.keyist.tech
    name: Ant Kaynak
  host:
    path: /
    address: localhost:8080
  api:
    version: v1
    name: Keyist Api Documentation
management:
  security: enabled:false
logging:
  level:
    org:
      hibernate:
        SQL: INFO
